### ISSUE TITLE
Warning: Class Configure can't be declared

### ISSUE THREAD

**Issue by maxleistner** [sixmonkey/sloth#6]
The following warning appears after every reload of a page in the /log/error.log
```
PHP Warning: Cannot declare class Configure, because the name is already in use in /var/www/html/vendor/sixmonkey/sloth/src/Core/Sloth.php:110
```

**Comment by sixmonkey** [comment]
Thanks for reporting this issue, I‘ll have a quick look for it this weekend.

**Comment by maxleistner** [comment]
Thanks for the hot fix - it does remove the error log and the problem 👍
