### ISSUE TITLE
Get layotter post_options

### ISSUE THREAD

**Issue by maxleistner** [sixmonkey/sloth#9]
I am trying to get the layotter element options within a module. If i debug the result of `$this->get( '_layotter.passed' );` i get the following: 
```
class => "1/2" (3)
col_options => array ()
row_options => array (4)
larger_width => false
background_color => "bg-white" (8)
row_margin => "my-2" (4)
row_padding => "py-2 py-md-4" (12)
post_options => array ()
``` 

The post_option array should now contain a field, which should return an array of objects selected within the element options screen. But it does not. 

How can i return the values of an element-options field within a module? 

![bildschirmfoto 2018-08-15 um 13 25 18](https://user-images.githubusercontent.com/7567185/44146160-b01ddc46-a08e-11e8-8e4b-aadda0e18ced.png)

**Comment by sixmonkey** [comment]
Sloth just takes all options passed by layotter and passes them on to your module. As far as I can see those element-options are not passed here: https://github.com/hingst/layotter/blob/1a6d0975ba04cc608b6f72e0136a24d94b8337e8/components/element.php#L319

That's a layotter issue as i see it…

**Comment by sixmonkey** [comment]
I'll close this issue for now – as soon as Dennis has fixed that in layotter, I'll implement it accordingly.
